services:
  - type: web
    name: youtube-tags-app
    runtime: python
    rootDir: ./web_app
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 4 --bind 0.0.0.0:$PORT backend.api:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
